### ISSUE TITLE
Failing to load PDB from Symbol Server 

### ISSUE THREAD

**Issue by forrestsmithfb** [RudjiGames/MTuner#100] opened 2023-08-24 23:00 UTC
I am unable to load the PDB for one of my programs from an internal symbol server. I can't figure out why. But `IDiaDataSource::loadDataForExe` is failing.

```
SYMSRV:  HttpQueryInfo(HTTP_QUERY_CONTENT_LENGTH): 800C2F76 - ERROR_HTTP_HEADER_NOT_FOUND
SYMSRV:  HttpQueryInfo: 80190190 - HTTP_STATUS_BAD_REQUEST
SYMSRV:  HTTPGET: /MYSERVERPATH/Foo.pdb/42A6E6342E735EB74C4C44205044422E1/Foo.pdb
SYMSRV:  HttpQueryInfo: 801900c8 - HTTP_STATUS_OK
SYMSRV:  RESULT: 0x00000000
SYMSRV:  BYINDEX: 0x2
         MYSERVERPATH
         Foo.pdb
         42A6E6342E735EB74C4C44205044422E1
SYMSRV:  HTTPGET: /MYSERVERPATH/Foo.pdb/42A6E6342E735EB74C4C44205044422E1/Foo.pdb
SYMSRV:  HttpQueryInfo: 801900c8 - HTTP_STATUS_OK
SYMSRV:  RESULT: 0x00000000
```

What's weird is that `42A6E6342E735EB74C4C44205044422E1` is the correct hash and Visual Studio is able to correctly load this pdb from my symbol server. I have a tool that runs `SymInitialize` on a running process and it also able to load the pdb.

I've never used `IDiaDataSource` before and don't know how it works. Stepping through the callbacks nothing stood out to me. It's ultimately returning `E_PDB_NOT_FOUND` even though

I also verified that I can download `Foo.pdb` simply by pasting the full URL in my browser. So it's the right URL. It's the right PDB. But `loadDataForExe` is failing? That's super super weird.

**Comment by forrestsmithfb** [comment] 2023-08-24 23:12
I just learned about `symchk`.

```
symchk.exe PATH/to/Foo.exe /s srv*MYSERVERPATH
```

Symchk is succeeding. And it fails if I do not specify the symbol server. I have no idea why `loadDataForExe` is not. Very strange.

**Comment by forrestsmithfb** [comment] 2023-08-26 08:58
Yeah. Microsoft symbol server libraries are all single threaded and crazy inefficient/slow. It's super frustrating and annoying.

**Comment by milostosic** [comment] 2024-11-23 18:25
duplicate of #97

**Closed** 2024-11-23 18:27 UTC
